### ISSUE TITLE
Usar Bootstrap para melhorar o front-end do site

### ISSUE THREAD

**Issue by LunaHenrique** [LBenati/dungeon-party#3]
Com o bootstrap fica mais fácil fazer o visual do site, e ele ainda acaba ficando melhor! Além disso ele ajuda muito no processo de permitir que o site seja responsivo.

**Comment by LBenati** [comment]
Muito obrigado, Luna! Já utilizei o Bootstrap e estarei subindo no repositório a nova versão do nosso código.
